name: Deploy Discord Bot

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull latest code
        run: |
          cd /opt/steve-bot  # change to your repo path
          git fetch origin
          git reset --hard origin/main

      - name: Install dependencies
        run: |
          cd /opt/steve-bot
          npm ci

      - name: Build project
        run: |
          cd /opt/steve-bot
          npm run build

      - name: Restart bot service
        run: |
          sudo systemctl restart discord-bot
