# .github/workflows/deploy.yml
name: Deploy Discord Bot

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (needed to access secrets, etc.)
        uses: actions/checkout@v4

      - name: Install cloudflared
        run: |
          curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o cloudflared
          chmod +x cloudflared
          sudo mv cloudflared /usr/local/bin/cloudflared

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          touch ~/.ssh/known_hosts

      - name: Connect via Cloudflare Tunnel and deploy
        env:
          CF_ACCESS_CLIENT_ID: ${{ secrets.CLOUDFLARE_CLIENT_ID }}
          CF_ACCESS_CLIENT_SECRET: ${{ secrets.CLOUDFLARE_CLIENT_SECRET }}
        run: |
          cloudflared access ssh --hostname ${{ secrets.SERVER_HOST }} \
            --id "$CF_ACCESS_CLIENT_ID" \
            --secret "$CF_ACCESS_CLIENT_SECRET" \
            --command "cd /opt/steve-bot && git pull origin main && npm install && npm run build && systemctl restart steve-bot"
